# AtomicBit theme for Starship - inspired by Oh My Posh AtomicBit theme
add_newline = true
continuation_prompt = "▶ "

# First line left side with programming language info on the right
format = "$os$username$hostname$directory$fill$nodejs$python$java$dotnet$golang$rust$dart$angular$ruby$julia$aws$kubernetes$battery$time$cmd_duration$line_break$git_branch$git_status$character"

# Configure individual components
[character]
success_symbol = "[╰─❯](bold green)"
error_symbol = "[╰─✗](bold red)"
vimcmd_symbol = "[╰─❮](bold yellow)"

[username]
style = "bold yellow"
format = "[╭─[$user]($style)"
show_always = true

[hostname]
style = "bold green"
format = "[@$hostname]─](bold green)"
ssh_only = false
ssh_symbol = "🌐 "

[directory]
style = "bold white"
format = "[[$path]](white) "
truncation_length = 3
truncation_symbol = "…/"

[fill]
symbol = " "

[git_branch]
style = "bold cyan"
format = "[[$symbol$branch]](bold cyan) "
symbol = "󰘬 "

[git_status]
format = "([[$all_status$ahead_behind]](bold white)) "
conflicted = "[󰞇](bold red)"
ahead = "[⇡${count}](bold green)"
behind = "[⇣${count}](bold red)"
diverged = "[⇕⇡${ahead_count}⇣${behind_count}](bold yellow)"
untracked = "[?${count}](bold yellow)"
stashed = "[*${count}](bold blue)"
modified = "[!${count}](bold yellow)"
staged = "[+${count}](bold green)"
renamed = "[»${count}](bold cyan)"
deleted = "[✘${count}](bold red)"

[nodejs]
format = "[$symbol($version )]($style)"
symbol = "󰎙 "
style = "bold green"

[python]
format = "[$symbol($version )]($style)"
symbol = "󰌠 "
style = "bold yellow"

[java]
format = "[$symbol($version )]($style)"
symbol = "☕ "
style = "bold red"

[dotnet]
format = "[$symbol($version )]($style)"
symbol = "󰪮 "
style = "bold blue"

[golang]
format = "[$symbol($version )]($style)"
symbol = "󰟓 "
style = "bold cyan"

[rust]
format = "[$symbol($version )]($style)"
symbol = "󱘗 "
style = "bold orange"

[dart]
format = "[$symbol($version )]($style)"
symbol = "󰴺 "
style = "bold blue"

[angular]
format = "[$symbol($version )]($style)"
symbol = "󰚲 "
style = "bold red"

[ruby]
format = "[$symbol($version )]($style)"
symbol = "󰴭 "
style = "bold red"

[julia]
format = "[$symbol($version )]($style)"
symbol = "ஃ "
style = "bold green"

[aws]
format = "[$symbol($profile )]($style)"
symbol = "󰸏 "
style = "bold yellow"

[kubernetes]
format = "[$symbol$context( \($namespace\))]($style)"
symbol = "☸ "
style = "bold blue"

[battery]
full_symbol = "󰁹 "
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
unknown_symbol = "󰂑 "
empty_symbol = "󰂎 "
format = "[[$symbol$percentage]](bold $style)─"
[[battery.display]]
threshold = 20
style = "red"
[[battery.display]]
threshold = 60
style = "yellow"
[[battery.display]]
threshold = 100
style = "green"

[time]
format = "[[$time]](bold cyan) "
time_format = "%H:%M"
disabled = false

[cmd_duration]
format = "took [[$duration]](bold yellow) "
min_time = 2000

[os]
format = "[$symbol]($style)"
style = "bold white"
disabled = false

[os.symbols]
Windows = "󰍲 "
Ubuntu = "󰕈 "
SUSE = "󰧡 "
Raspbian = "󰐿 "
Mint = "󰣭 "
Macos = "󰀵 "
Manjaro = "󰣛 "
Linux = "󰌽 "
Gentoo = "󰣨 "
Fedora = "󰣲 "
Alpine = "󰣩 "
Amazon = "󰣵 "
Android = "󰀲 "
Arch = "󰣇 "
CentOS = "󰣪 "
Debian = "󰣚 "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "

[line_break]
disabled = false
