[mgr]
ratio = [1, 4, 3]
sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true
linemode = "size"
show_hidden = false
show_symlink = true

[preview]
tab_size = 2
max_width = 1000
max_height = 1000
cache_dir = ""
image_filter = "triangle"
image_quality = 75

[opener]
folder = [{ exec = "$EDITOR ." }]
archive = [{ exec = "unar -d \"$1\"", desc = "Extract here" }]
pdf = [
    { exec = "open -a Preview \"$1\"", desc = "Open in Preview" },
    { exec = "open -a \"Adobe Acrobat Reader\" \"$1\"", desc = "Open in Adobe Reader" },
]
text = [{ exec = "$EDITOR \"$1\"" }]
image = [{ exec = "open -a Preview \"$1\"", desc = "Open in Preview" }]
video = [{ exec = "open -a IINA \"$1\"", desc = "Open in IINA" }]
audio = [{ exec = "open -a IINA \"$1\"", desc = "Open in IINA" }]
fallback = [{ exec = "open \"$1\"", desc = "Open with system default" }]

[plugin]
prepend_previewers = []
append_previewers = []
prepend_readers = []
append_readers = []

[input]
cd_title = "Change directory:"
cd_origin = "cwd"
cd_completions = []

[select]
open_title = "Open with:"

[tasks]
micro_workers = 5
macro_workers = 10
bizarre_retry = 5

[plugin.preview]
syntax_highlight = true
max_size = 10485760  # 10MB
max_lines = 10000
